AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Moon Chatbot API

Resources:
  MoonChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.8
      CodeUri: src/
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        OPENAI_API_KEY: !Ref OpenAIAPIKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /ask
            Method: post

Parameters:
  OpenAIAPIKey:
    Type: String
    Description: OpenAI API Key for accessing the OpenAI service

Outputs:
  MoonChatbotApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MoonChatbotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ask"